<?php

namespace JobBundle\Repository;

/**
 * JobsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobsRepository extends \Doctrine\ORM\EntityRepository
{
}
